# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bounty Hunter Space Besties
email: andrewehipp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Paget and Cory hate being Criminal Acquisition Specialists. They took this
    job thinking they’d go on adventures and get to see the universe, but so far
    they’ve just seen a lot of embezzlers and tax evaders. When they are
    transferred to a new sector that’s known as the Wild West of the universe,
    they see it as fresh start and a chance to see some real action, but they
    find themselves in over their heads when the agree to clear the name of a
    shapeshifter accused of murdering his magical peers. Hilarity ensues.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bountyhunterspacebesties.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
appID: 487393568131319
patreon: https://www.patreon.com/chipp

# Build settings
markdown: kramdown
gems:
    - jekyll-feed
exclude:
    - node_modules
    - resources
    - Gemfile
    - Gemfile.lock
sass:
    style: compressed
collections:
    posts:
        layout: post
        output:   true
        permalink: /blog/:year/:title/
    comic:
        layout: comic
        output:   true
        permalink: /comic/:title/
